

waifuname = ["Ram","Rem","Mai sakurajime","Nezuko kamado","Chika Fujiwara","Asuna","Alice zuberg","Sinon","Saber","Nakiri erina","Mizuhara chizuru","Zero Two","Alice Nakri","Tadokoro Megumi","Utaha kasumigaoka","Makise kurisu","Rias Gremory","Shinobu kocho","Yumeko Jabami","Violet evergarden"
,"Erza Scarlet ","Isuzu sento","Mitsuha miyamizu","Nami","Hori Kyoko","Shimizu Kiyoko","Hatsuna miku ","Aqua ","Shina mashiro ","Rinko yamato","Mio Akiyama","Sakura matou ","Eru chitanda","Momo deviluke","Hitagi Senjougahara","Tsubasa Hanekawa","Yotsugi Ononoki","Suruga Kanbaru","Shinobu Oshino"]

waifuseries = ["Re:zero","Re:zero","Rascal does not dreams of bunny girl senpai","Demon slayer","Kaguya sama love is war","Sword art online","Sword art online"
,"Sword art online","Fate zero/stay night","Food wars","Rent A Girlfriend","Darling in the franxx","Food wars","Food wars","Saenai heroine no sodatekata","Steins;Gate","High school dxd","Demon Slayer"
,"Kakegurui","Violet evergarden","Fairy Tail","Amagi brilliant park","Your name","One piece","Horimiya","Haikyuu","Vocaloid","KonoSuba: God's Blessing","Pet girl of sakurasou","Ore Monogatari","K-On","Fate/stay night","Hyouka","To love-ru darkness","Bakemonogatari","Bakemonogatari","Nisemonogatari","Bakemonogatari","Bakemonogatari"]


waifuno = ["1","2","3","4","5","6","7","8","9","10","11","12","13","14","15","16","17","18","19","20","21","22","23","24","25","26","27","28","29","30","31","32","33","34","35","36","37","38"]

waifupics = ["https://i.imgur.com/f2ctAMd.png","https://i.imgur.com/oJasp3x.jpg","https://i.imgur.com/N4PErdx.png","https://i.imgur.com/hZR56Cz.png","https://i.imgur.com/y5QMvHo.png","https://i.imgur.com/jlxeHeZ.jpg","https://i.imgur.com/ohuL5DF.png","https://i.imgur.com/2DVJA6I.png","https://i.imgur.com/kn2zVPY.png","https://i.imgur.com/Q3H61vv.png","https://i.imgur.com/Twr9bdH.png","https://i.imgur.com/mcHzmf2.png","https://i.imgur.com/U0dsLJG.png","https://i.imgur.com/eyvbjLw.png","https://i.imgur.com/Km1YKHu.png",
"https://i.imgur.com/iDhLwBC.png","https://i.imgur.com/DzmeI9R.png","https://i.imgur.com/TB6MgOP.png","https://i.imgur.com/h12ACW7.png","https://i.imgur.com/ohO6Erg.png","https://i.imgur.com/TtNX5FR.png","https://i.imgur.com/rpl5IEf.png","https://i.imgur.com/dSscchO.png","https://i.imgur.com/wBrQHbt.png","https://i.imgur.com/z1znrGZ.png","https://i.imgur.com/PWJcWcY.png","https://i.imgur.com/SRBrJHd.png","https://i.imgur.com/904liEq.png","https://i.imgur.com/VgKbU6V.png","https://i.imgur.com/dqPghGx.png",
"https://i.imgur.com/4K6GNng.png","https://i.imgur.com/1Xq1Iii.png","https://i.imgur.com/UeVyhON.png","https://i.imgur.com/ycpnBY2.png","https://i.imgur.com/VC1Q6uG.png","https://i.imgur.com/k4tQdhp.png?1","https://i.imgur.com/nHGNWW6.png","https://i.imgur.com/VsZLW5y.png","https://i.imgur.com/gEKAXAI.png"]